CREATE TABLE [dbo].[Customer]
(
	[CustID] NVARCHAR (10) NOT NULL,
	[FullName] NVARCHAR (100) NOT NULL,
	[SegID] INT NOT NULL,
	[Country] NVARCHAR (50) NOT NULL,
	[City] NVARCHAR (50) NOT NULL,
	[State] NVARCHAR (50) NOT NULL,
	[PostCode] INT NOT NULL,
	[Region] NVARCHAR (50) NULL,
	CONSTRAINT PK_CustID PRIMARY KEY (CustID),
	CONSTRAINT FK_SegID FOREIGN KEY (SegID) REFERENCES Segment (SegID),
	CONSTRAINT FK_Region FOREIGN KEY (Region) REFERENCES Region (Region)
)
