CREATE TABLE [dbo].[Order]
(
	[CustID] NVARCHAR (10) NOT NULL,
	[ProdID] NVARCHAR (50) NOT NULL,
	[OrderDate] DATE NOT NULL,
	[Quantity] INT NOT NULL,
	[ShipDate] DATE NOT NULL,
	[ShipMode] NVARCHAR (20) NOT NULL,
	CONSTRAINT PK_ORDER PRIMARY KEY (CustID, ProdID, OrderDate),
	CONSTRAINT FK_CUSTOMER FOREIGN KEY (CustID) REFERENCES Customer (CustID),
	CONSTRAINT FK_PRODUCT FOREIGN KEY (ProdID) REFERENCES Product (ProdID),
	CONSTRAINT FK_SHIPPING FOREIGN KEY (ShipMode) REFERENCES Shipping (ShipMode)

)
